ALTER TABLE public.tenant_onboarding_request
    ADD COLUMN IF NOT EXISTS license_number VARCHAR(80) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS state VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS supporting_docs VARCHAR(1200) NOT NULL DEFAULT '';
