FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY . .
RUN ./mvnw -pl sevacare-api -am -DskipTests clean package -q

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/sevacare-api/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
