FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ENV EXPO_PUBLIC_API_BASE_URL=http://localhost:8081/api/v1
RUN npx expo export --platform web

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve@14
COPY --from=build /app/dist ./dist
EXPOSE 8087
CMD ["serve", "-s", "dist", "-l", "8087"]
